# File: /.swiftlint.yml

disabled_rules:
  - line_length
  - identifier_name
  - trailing_whitespace
  - todo
  - file_length

opt_in_rules:
  - empty_count
  - unused_declaration

included:
  - App
  - Model
  - ViewModel
  - View
  - Engine
  - Extensions
  - Shared

swiftlint_version: 0.54.0
